# yaml-language-server: $schema=https://blue-build.org
name: bazzite-omen-kde
description: This is my personal OS image.

base-image: ghcr.io/ublue-os/bazzite-nvidia-open
image-version: testing

modules:
  - type: script
    snippets:
      - mkdir -p /opt/virtualbox-kvm
      - curl -L \
          -o /opt/virtualbox-kvm/VirtualBox-KVM.AppImage \
          "https://github.com/ivan-hc/VirtualBox-appimage"
      - chmod +x /opt/virtualbox-kvm/VirtualBox-KVM.AppImage
  - type: files
    files:
      - source: system
        destination: /

  - type: default-flatpaks
    configurations:
      - notify: true
        scope: system
        install:
          - com.heroicgameslauncher.hgl
          - org.onlyoffice.desktopeditors # Dodano ONLYOFFICE

  - type: dnf
    install:
      packages:
        - easyeffects
        - git
        - gcc
        - make
        - dkms
        - kernel-devel
        - mc
        - python3-pyqt6
        - python3-pyside6
        - python3-tkinter
        - brave-browser
        - darkly

  - type: signing
