import "../js/CategoryManager.js" as CategoryManager
import "../js/ConfigManager.js" as ConfigManager
import "../js/HistoryManager.js" as HistoryManager
import "../js/PinnedManager.js" as PinnedManager
import "../js/RSSManager.js" as RSSManager
import "../js/TelemetryManager.js" as TelemetryManager
import "../js/utils.js" as Utils
import QtCore
import QtQuick
import org.kde.plasma.core as PlasmaCore
import org.kde.plasma.plasma5support as Plasma5Support
import org.kde.plasma.plasmoid

Item {
    // trFunc property removed
    // pinnedItemsChanged is automatically generated by property definition
    // Use the debug overlay's datasource pattern or similar mechanism if available
    // Since we don't have a global DataSource, we need to expose one here or usage site.
    // But for "Open With", "Trash", "Open Location", we need shell commands.
    // We will assume the view creates a DataSource for this purpose.
    // Or we can add one here.

    id: logicRoot

    // Required dependencies
    required property var plasmoidConfig
    // Reactive version counter for deep updates
    property int historyVersion: 0
    // ===== CONFIGURATION MANAGEMENT =====
    readonly property int userProfile: plasmoidConfig.userProfile || 0
    readonly property var profileDefaults: ConfigManager.getProfileDefaults(userProfile)
    readonly property int maxHistoryItems: ConfigManager.getMaxHistoryItems(userProfile)
    // Feature flags based on profile
    readonly property bool debugEnabled: ConfigManager.isFeatureEnabled(userProfile, "debug")
    readonly property bool previewEnabled: ConfigManager.isFeatureEnabled(userProfile, "preview")
    readonly property bool advancedSearchEnabled: ConfigManager.isFeatureEnabled(userProfile, "advancedSearch")
    readonly property bool telemetryEnabled: ConfigManager.isFeatureEnabled(userProfile, "telemetry")
    readonly property bool categoryPriorityEnabled: ConfigManager.isFeatureEnabled(userProfile, "categoryPriority")
    readonly property bool activityPinningEnabled: ConfigManager.isFeatureEnabled(userProfile, "activityPinning")
    // ===== HISTORY MANAGEMENT =====
    property var searchHistory: []
    // ===== PINNED ITEMS MANAGEMENT =====
    property var pinnedItems: []
    property string currentActivityId: "global"
    // ===== CATEGORY SETTINGS =====
    property var categorySettings: {
    }
    // ===== TELEMETRY =====
    property var telemetryStats: TelemetryManager.getStatsObject(plasmoidConfig.telemetryData || "{}")
    // Reactive property for bindings
    readonly property var visiblePinnedItems: PinnedManager.getPinnedForActivity(pinnedItems, currentActivityId)
    // Activity management
    readonly property string currentActivityName: currentActivityId === "global" ? "Global" : currentActivityId
    // ===== DEPENDENCY CHECKS =====
    property bool manInstalled: true
    // ===== RSS MANAGEMENT =====
    property var rssSources: []
    property var rssCache: []
    property var rssTickerEntries: []
    readonly property bool rssEnabled: plasmoidConfig.rssEnabled || false
    readonly property string rssCacheBase: {
        var path = StandardPaths.writableLocation(StandardPaths.CacheLocation) + "/com.mcc45tr.filesearch/rss";
        if (path.indexOf("file://") === 0) {
            return path.replace(/^file:\/\/\/?/, "/");
        }
        return path;
    }
    property var syncQueue: []
    property bool isSyncing: false

    // Signals
    signal historyForceUpdate()

    // Config validation
    function validateConfig() {
        return ConfigManager.sanitizeConfig({
            "displayMode": plasmoidConfig.displayMode,
            "viewMode": plasmoidConfig.viewMode,
            "iconSize": plasmoidConfig.iconSize,
            "listIconSize": plasmoidConfig.listIconSize,
            "previewEnabled": plasmoidConfig.previewEnabled,
            "debugOverlay": plasmoidConfig.debugOverlay,
            "userProfile": plasmoidConfig.userProfile
        });
    }

    function getRecommendedIconSize() {
        return ConfigManager.getRecommendedIconSize(plasmoidConfig.displayMode, plasmoidConfig.viewMode);
    }

    // ===== HISTORY FUNCTIONS =====
    function loadHistory() {
        // Debug: console.log("FileSearch [History]: Loading history...")
        searchHistory = HistoryManager.loadHistory(plasmoidConfig.searchHistory);
    }

    function saveHistory() {
        plasmoidConfig.searchHistory = JSON.stringify(searchHistory);
    }

    function addToHistory(display, decoration, category, matchId, filePath, sourceType, queryText) {
        searchHistory = HistoryManager.addToHistory(searchHistory, display, decoration, category, matchId, filePath, sourceType, queryText, plasmoidConfig.maxHistoryItems);
        saveHistory();
        // Schedule delayed icon check (1s)
        if (searchHistory.length > 0) {
            iconCheckTimer.uuid = searchHistory[0].uuid;
            iconCheckTimer.filePath = filePath;
            iconCheckTimer.decoration = decoration;
            iconCheckTimer.category = category;
            iconCheckTimer.restart();
        }
    }

    function formatHistoryTime(timestamp) {
        return Utils.formatHistoryTime(timestamp, function(s) { return i18nd("plasma_applet_com.mcc45tr.filesearch", s); });
    }

    function clearHistory() {
        searchHistory = HistoryManager.clearHistory();
        saveHistory();
    }

    function removeFromHistory(uuid) {
        searchHistory = HistoryManager.removeFromHistory(searchHistory, uuid);
        saveHistory();
    }

    // Shell escape helper - delegates to Utils.shellEscape
    function shellEscape(str) {
        return Utils.shellEscape(str)
    }

    // Launch a .desktop application safely
    function launchApp(filePath) {
        if (!filePath) return
        runShellCommand("kioclient exec " + shellEscape(filePath.toString()))
    }

    // Show file/app properties dialog safely
    function showProperties(filePath) {
        if (!filePath) return
        runShellCommand("kioclient openProperties " + shellEscape(filePath.toString()))
    }

    function runShellCommand(cmd) {
        if (!cmd)
            return ;

        globalShellSource.connectSource(cmd);
    }

    // ===== FILE OPERATIONS =====
    function openFolder(url) {
        if (!url)
            return ;

        var path = url.toString();
        // Use D-Bus to open file manager and select the item
        var cmd = "dbus-send --session --dest=org.freedesktop.FileManager1 /org/freedesktop/FileManager1 org.freedesktop.FileManager1.ShowItems array:string:" + shellEscape(path) + " string:\"\"";
        runShellCommand(cmd);
    }

    function copyToClipboard(text) {
        if (!text)
            return ;

        // Using a reliable shell command for clipboard since QML clipboard is restricted in some environments
        var escaped = shellEscape(text);
        var cmd = "echo -n " + escaped + " | xclip -selection clipboard || echo -n " + escaped + " | wl-copy";
        runShellCommand(cmd);
    }

    function moveToTrash(url) {
        if (!url)
            return ;

        var path = url.toString();
        var cmd = "kioclient move " + shellEscape(path) + " trash:/";
        runShellCommand(cmd);
    }

    function openTerminal(url) {
        if (!url)
            return ;

        var path = url.toString().replace("file://", "");
        // If it's a file, get its directory
        if (path.indexOf(".") !== -1 && path.lastIndexOf("/") < path.lastIndexOf("."))
            path = path.substring(0, path.lastIndexOf("/"));

        var cmd = "konsole --workdir " + shellEscape(path);
        runShellCommand(cmd);
    }

    function fetchDirectoryIcon(folderPath, uuid) {
        if (!folderPath || folderPath.toString().indexOf("file://") !== 0)
            return ;

        var path = folderPath.toString().replace(/^file:\/\/\/?/, "/");
        if (path.slice(-1) === "/")
            path = path.slice(0, -1);

        var dotDirPath = path + "/.directory";
        var cmd = "cat " + shellEscape(dotDirPath) + " 2>/dev/null";
        
        executable.callbacks[cmd] = function(stdout) {
            var lines = stdout.split('\n');
            for (var i = 0; i < lines.length; i++) {
                var line = lines[i].trim();
                if (line.indexOf("Icon=") === 0) {
                    var iconName = line.substring(5).trim();
                    if (iconName.length > 0) {
                        if (HistoryManager.updateItemIcon(logicRoot.searchHistory, uuid, iconName)) {
                            logicRoot.saveHistory();
                            logicRoot.historyForceUpdate();
                        }
                        return ;
                    }
                }
            }
        };
        executable.connectSource(cmd);
    }

    // ===== PINNED FUNCTIONS =====
    function loadPinned() {
        // Debug: console.log("FileSearch [Pinned]: Loading pinned items...")
        pinnedItems = PinnedManager.loadPinned(plasmoidConfig.pinnedItems);
    }

    function savePinned() {
        plasmoidConfig.pinnedItems = PinnedManager.savePinned(pinnedItems);
    }

    function pinItem(item) {
        pinnedItems = PinnedManager.pinItem(pinnedItems, item, currentActivityId);
        savePinned();
        pinnedItemsChanged();
    }

    function unpinItem(matchId) {
        pinnedItems = PinnedManager.unpinItem(pinnedItems, matchId, currentActivityId);
        savePinned();
        pinnedItemsChanged();
    }

    function isPinned(matchId) {
        return PinnedManager.isPinned(pinnedItems, matchId, currentActivityId);
    }

    function togglePin(item) {
        pinnedItems = PinnedManager.togglePin(pinnedItems, item, currentActivityId);
        savePinned();
        pinnedItemsChanged();
    }

    function getVisiblePinnedItems() {
        return visiblePinnedItems;
    }

    function getPinInfo(matchId) {
        return PinnedManager.getPinInfo(pinnedItems, matchId, currentActivityId);
    }

    function reorderPinnedItems(fromIndex, toIndex) {
        pinnedItems = PinnedManager.reorderPinned(pinnedItems, fromIndex, toIndex);
        savePinned();
        pinnedItemsChanged();
    }

    function setActivity(activityId) {
        currentActivityId = activityId || "global";
    }

    function pinItemToActivity(item, activityId) {
        pinnedItems = PinnedManager.pinItem(pinnedItems, item, activityId || "global");
        savePinned();
        pinnedItemsChanged();
    }

    // ===== CATEGORY SETTINGS FUNCTIONS =====
    function loadCategorySettings() {
        // Debug: console.log("FileSearch [Category]: Loading category settings...")
        categorySettings = CategoryManager.loadCategorySettings(plasmoidConfig.categorySettings);
    }

    function processCategories(categories) {
        return CategoryManager.processCategories(categories, categorySettings);
    }

    function isCategoryVisible(categoryName) {
        return CategoryManager.isCategoryVisible(categorySettings, categoryName);
    }

    function getEffectiveIcon(categoryName, defaultIcon) {
        return CategoryManager.getEffectiveIcon(categorySettings, categoryName, defaultIcon);
    }

    function updateTelemetry(latency) {
        var newData = TelemetryManager.recordSearch(plasmoidConfig.telemetryData || "{}", latency);
        plasmoidConfig.telemetryData = newData;
        telemetryStats = TelemetryManager.getStatsObject(newData);
    }

    function checkManAvailability() {
        manCheckSource.connectedSources = ["command -v man"];
    }

    function loadRSS() {
        try {
            rssSources = JSON.parse(plasmoidConfig.rssSources || "[]");
            rssCache = JSON.parse(plasmoidConfig.rssCache || "[]");
            rebuildRssTickerEntries();
        } catch (e) {
            rssSources = [];
            rssCache = [];
            rssTickerEntries = [];
        }
    }

    function rebuildRssTickerEntries() {
        var cache = Array.isArray(rssCache) ? rssCache : [];
        if (cache.length === 0) {
            rssTickerEntries = [];
            return;
        }

        var grouped = {};
        var sourceOrder = [];
        for (var i = 0; i < cache.length; i++) {
            var entry = cache[i];
            if (!entry || !entry.display || entry.display.length <= 3)
                continue;

            var subtext = entry.subtext || "";
            var sourceName = subtext.split(" | ")[0] || "Unknown";
            if (!grouped[sourceName]) {
                grouped[sourceName] = [];
                sourceOrder.push(sourceName);
            }
            grouped[sourceName].push({
                text: entry.display,
                source: sourceName
            });
        }

        var mixed = [];
        var offset = 0;
        // Limit to 40 items for ticker to avoid heavy memory usage
        while (mixed.length < 40) {
            var added = false;
            for (var j = 0; j < sourceOrder.length; j++) {
                var source = sourceOrder[j];
                var sourceEntries = grouped[source];
                if (sourceEntries && offset < sourceEntries.length) {
                    mixed.push(sourceEntries[offset]);
                    added = true;
                    if (mixed.length >= 40)
                        break;
                }
            }
            if (!added)
                break;
            offset++;
        }

        rssTickerEntries = mixed;
    }

    function finalizeUpdate(combined, markAsFresh) {
        // Sort chronologically (newest first)
        combined.sort(function(a, b) {
            var da = a.rawDate ? new Date(a.rawDate).getTime() : 0;
            var db = b.rawDate ? new Date(b.rawDate).getTime() : 0;
            return db - da; // Descending
        });
        
        rssCache = combined;
        // Optimization: Do NOT serialize the massive RSS cache string back to plasmoidConfig
        // to prevent Plasma shell stutters during synchronous KConfig writing.
        if (markAsFresh)
            plasmoidConfig.rssLastSyncAll = new Date().getTime();
        
        rebuildRssTickerEntries();
    }

    function getSourceFilePath(url) {
        return RSSManager.getSourceFilePath(url, rssCacheBase);
    }

    function clearRssCache() {
        var cmd = "rm -rf " + shellEscape(rssCacheBase) + " && mkdir -p " + shellEscape(rssCacheBase);
        executable.connectSource(cmd);
        rssCache = [];
        rssTickerEntries = [];
        // Set to empty string instead of writing JSON array representation to KConfig
        plasmoidConfig.rssCache = "";
        plasmoidConfig.rssLastSyncAll = 0;
        
        // Reset lastSync for all sources
        for (var i = 0; i < rssSources.length; i++) {
            rssSources[i].lastSync = 0;
        }
        plasmoidConfig.rssSources = JSON.stringify(rssSources);
    }

    function loadSourceEntries(url, callback) {
        if (!url) {
            callback([]);
            return ;
        }
        var path = getSourceFilePath(url);
        
        var xhr = new XMLHttpRequest();
        xhr.onreadystatechange = function() {
            if (xhr.readyState === XMLHttpRequest.DONE) {
                if (xhr.status === 200 || xhr.status === 0) {
                    var raw = xhr.responseText.trim();
                    if (!raw) {
                        callback([]);
                        return;
                    }
                    
                    try {
                        // Attempt base64 decode first
                        var decodedJson = RSSManager.decodeBase64(raw);
                        if (decodedJson && (decodedJson.indexOf("[") !== -1 || decodedJson.indexOf("{") !== -1)) {
                            var data = JSON.parse(decodedJson);
                            callback(Array.isArray(data) ? data : []);
                        } else {
                            // Try parsing raw if base64 didn't look like JSON
                            var rawData = JSON.parse(raw);
                            callback(Array.isArray(rawData) ? rawData : []);
                        }
                    } catch (e) {
                        // Final attempt: raw JSON
                        try {
                            var rawData2 = JSON.parse(raw);
                            callback(Array.isArray(rawData2) ? rawData2 : []);
                        } catch (e2) {
                            console.warn("LogicController: Failed to read/parse RSS cache for", url);
                            callback([]);
                        }
                    }
                } else {
                    callback([]);
                }
            }
        };
        xhr.open("GET", "file://" + path);
        xhr.send();
    }

    function checkAndSyncRSS() {
        if (!rssEnabled || rssSources.length === 0)
            return ;

        var now = new Date().getTime();
        for (var i = 0; i < rssSources.length; i++) {
            var source = rssSources[i];
            var interval = source.syncInterval || plasmoidConfig.rssSyncInterval || 60;
            var intervalMs = interval * 60 * 1000;
            var lastSync = source.lastSync || 0;
            if (now - lastSync > intervalMs)
                syncSource(i);

        }
    }

    function syncSource(index) {
        if (syncQueue.indexOf(index) === -1)
            syncQueue.push(index);

        if (!isSyncing) {
            isSyncing = true;
            // Start queue processing. Only restart the timer - do NOT manually
            // call triggered() as that causes the first item to be processed twice.
            processQueueTimer.restart();
        }
    }

    function syncSourceSingle(index) {
        var source = rssSources[index];
        if (!source || !source.url)
            return ;

        var scriptPath = getScriptPath();
        var max = source.maxEntries || plasmoidConfig.rssMaxEntries || 10;
        var cmd = "sh " + shellEscape(scriptPath) + " " + shellEscape(rssCacheBase) + " " + shellEscape(source.url) + " " + shellEscape(source.name) + " " + shellEscape(String(max));
        
        executable.callbacks[cmd] = function(stdout) {
            if (stdout.indexOf("SUCCESS") !== -1) {
                rssSources[index].lastSync = new Date().getTime();
                plasmoidConfig.rssSources = JSON.stringify(rssSources);
            }
        };
        executable.connectSource(cmd);
    }

    // New non-blocking sync for config UI usage
    function syncSourceBackground(index, callback) {
        var source = rssSources[index];
        if (!source || !source.url) {
            if (callback) callback("FAIL: Invalid source");
            return;
        }

        var scriptPath = getScriptPath();
        var max = source.maxEntries || plasmoidConfig.rssMaxEntries || 10;
        var cmd = "sh " + shellEscape(scriptPath) + " " + shellEscape(rssCacheBase) + " " + shellEscape(source.url) + " " + shellEscape(source.name) + " " + shellEscape(String(max));
        
        executable.callbacks[cmd] = function(stdout) {
            var lines = stdout.split("\n");
            for (var i = 0; i < lines.length; i++) {
                var line = lines[i].trim();
                if (line && callback) callback(line, cmd);
            }
        };
        executable.connectSource(cmd);
    }
    
    function getScriptPath() {
        var path = Qt.resolvedUrl("../../tools/rss_sync.sh").toString();
        if (path.indexOf("file://") === 0) {
            return path.replace(/^file:\/\/\/?/, "/");
        }
        return path;
    }

    function syncAllRSS() {
        if (!rssEnabled || rssSources.length === 0)
            return ;

        for (var i = 0; i < rssSources.length; i++) {
            syncSource(i);
        }
    }

    function updateCombinedCache(markAsFresh) {
        var combined = [];
        var completedCount = 0;
        var totalSources = rssSources.length;

        if (totalSources === 0) {
            rssCache = [];
            rssTickerEntries = [];
            return ;
        }

        for (var i = 0; i < totalSources; i++) {
            (function(index) {
                var url = rssSources[index].url;
                loadSourceEntries(url, function(entries) {
                    if (entries && Array.isArray(entries)) {
                        combined = combined.concat(entries);
                    }
                    completedCount++;
                    if (completedCount === totalSources) {
                        finalizeUpdate(combined, markAsFresh);
                    }
                });
            })(i);
        }
    }

    function hashStr(s) {
        var hash = 0;
        for (var i = 0; i < s.length; i++) {
            hash = ((hash << 5) - hash) + s.charCodeAt(i);
            hash |= 0;
        }
        return Math.abs(hash);
    }

    function parseRSS(xml, sourceName) {
        return RSSManager.parseRSS(xml, sourceName);
    }

    // Runs a non-blocking stat + head command to retrieve both file size
    // and the first 20KB of local text files securely without RAM/CPU overhead.
    function readLocalTextSnippet(filePath, callback) {
        var path = filePath.toString();
        if (path.startsWith("file://")) path = path.substring(7);
        path = path.trim();
        if (!path) {
            callback("", 0);
            return;
        }
        var cmd = "stat -c %s " + shellEscape(path) + " && echo '---SIZE_END---' && head -c 20000 " + shellEscape(path);
        executable.callbacks[cmd] = function(stdout) {
            var delimiter = "---SIZE_END---";
            var idx = stdout.indexOf(delimiter);
            if (idx !== -1) {
                var sizePart = stdout.substring(0, idx).trim();
                var contentPart = stdout.substring(idx + delimiter.length);
                if (contentPart.startsWith("\n")) {
                    contentPart = contentPart.substring(1);
                }
                var bytes = parseInt(sizePart, 10) || 0;
                callback(contentPart, bytes);
            } else {
                callback(stdout, 0);
            }
        };
        executable.connectSource(cmd);
    }

    onHistoryForceUpdate: historyVersion++ // Increment version to trigger bindings
    Component.onCompleted: {
        loadHistory();
        loadPinned();
        loadCategorySettings();
        loadRSS();
        updateCombinedCache(false);
        checkManAvailability();
        // Initial sync check
        Qt.callLater(() => {
            checkAndSyncRSS();
        });
    }

    // Global DataSource for shell commands
    Plasma5Support.DataSource {
        id: globalShellSource

        engine: "executable"
        connectedSources: []
        onNewData: (source, data) => {
            disconnectSource(source);
        }
    }

    // ===== ICON CHECK TIMER =====
    Timer {
        id: iconCheckTimer

        property string uuid
        property string filePath
        property string decoration
        property string category

        interval: 1000
        repeat: false
        onTriggered: {
            if (!uuid)
                return ;

            /// Only check if it has a file path
            if (filePath && filePath.toString().indexOf("file://") === 0) {
                // If decoration is broken (QIcon()) or missing
                if (decoration === "QIcon()" || decoration === "") {
                    // Set default folder icon temporarily if it's likely a folder
                    var isFolder = (category.toLowerCase().indexOf("place") !== -1 || category.toLowerCase().indexOf("folder") !== -1 || category.toLowerCase().indexOf("yerler") !== -1 || category.toLowerCase().indexOf("klasör") !== -1);
                    if (isFolder) {
                        HistoryManager.updateItemIcon(searchHistory, uuid, "folder");
                        saveHistory();
                        historyForceUpdate();
                    }
                    // Try to fetch custom icon from .directory file
                    fetchDirectoryIcon(filePath, uuid);
                }
            }
        }
    }

    Plasma5Support.DataSource {
        id: manCheckSource

        engine: "executable"
        connectedSources: []
        onNewData: (source, data) => {
            if (data["exit code"] !== undefined) {
                logicRoot.manInstalled = (data["exit code"] === 0);
                disconnectSource(source);
            }
        }
    }

    Plasma5Support.DataSource {
        id: executable

        property var callbacks: ({})

        engine: "executable"
        connectedSources: []
        onNewData: (source, data) => {
            var stdout = data["stdout"] || "";
            var lines = stdout.split("\n");
            
            var callback = callbacks[source];
            if (callback) {
                callback(stdout); // Keeping compatibility with single-string callbacks
                
                // Final state checks
                if (stdout.indexOf("SUCCESS") !== -1 || stdout.indexOf("FAIL:") !== -1 || data["exit code"] !== undefined) {
                    delete callbacks[source];
                    disconnectSource(source);
                }
            } else {
                // Fallback for partial source matches
                for (var key in callbacks) {
                    if (source.indexOf(key) !== -1 || key.indexOf(source) !== -1) {
                        var cb = callbacks[key];
                        if (typeof cb === "function") {
                            cb(stdout);
                        }
                        if (stdout.indexOf("SUCCESS") !== -1 || stdout.indexOf("FAIL:") !== -1 || data["exit code"] !== undefined) {
                            delete callbacks[key];
                            disconnectSource(source);
                        }
                        break;
                    }
                }
            }
        }
    }

    Timer {
        id: processQueueTimer

        interval: 1500
        repeat: true
        running: false
        onTriggered: {
            if (syncQueue.length === 0) {
                running = false;
                isSyncing = false;
                updateCombinedCache(true);
                return ;
            }
            var index = syncQueue.shift();
            if (rssSources[index] && rssSources[index].url)
                syncSourceSingle(index);

        }
    }

    Timer {
        id: rssSyncTimer

        interval: 60000 // Check every minute
        running: rssEnabled
        repeat: true
        onTriggered: checkAndSyncRSS()
    }

    // Watch for config changes (source addition/removal)
    Connections {
        function onRssSourcesChanged() {
            loadRSS();
            if (rssEnabled)
                syncAllRSS();
            else
                updateCombinedCache(false);

        }

        function onRssEnabledChanged() {
            if (rssEnabled)
                syncAllRSS();
            else
                updateCombinedCache(false);

        }

        target: plasmoidConfig
    }

}
